import {Container} from '@chakra-ui/react'
import Footer from '@components/Footer'
import Head from 'next/head'
import {NavUser} from '@components/Nav'

export const Layout = ({hasNavbar = true, hasFooter = true, children}) => (
  <Container maxWidth="container.lg">
    <Head>
      <title>Loman</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={'/favicon.ico'} />
    </Head>

    {hasNavbar && (
      <header>
        <NavUser />
      </header>
    )}

    {children}

    {hasFooter && (
      <footer>
        <Footer />
      </footer>
    )}
  </Container>
)
