import Head from 'next/head'
import {Container} from '@chakra-ui/react'

import {Nav} from '@components/Nav'

export default function Home() {
  return (
    <Container maxWidth="container.lg">
      <Head>
        <title>Loman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Nav />
      </header>
    </Container>
  )
}
